import os
import sys
import re
from pathlib import Path
from collections import defaultdict

def extract_source_info(filename):
    """
    Parses filenames generated by preprocess_mixed_data.py:
    Format: {prefix}_{source_stem}_crop{idx}.jpg or {prefix}_{video_name}_f{frame}_crop{idx}.jpg
    """
    # Remove file extension and crop suffix (_crop0, _crop1)
    base = Path(filename).stem
    base_no_crop = re.sub(r'_crop\d+$', '', base)
    
    # Try to extract video frame pattern (_f10, _f20, etc.)
    base_no_frame = re.sub(r'_f\d+$', '', base_no_crop)
    
    # Extract subject ID patterns if present (e.g., s0001, subject01, sub_05, etc.)
    subject_match = re.search(r'(subject[_\-]?\d+|sub[_\-]?\d+|s\d{3,4}|\d{2}_\d{2})', base, re.IGNORECASE)
    subject_id = subject_match.group(0).lower() if subject_match else None
    
    return {
        "full_filename": filename,
        "source_file_stem": base_no_frame,  # Unique source image/video file
        "subject_id": subject_id             # Extracted subject/person ID if available
    }

def audit_dataset_leakage(dataset_dir="processed_dataset"):
    """
    Audits processed_dataset/train and processed_dataset/val to detect data leakage.
    Checks:
    1. Source file leakage (same image/video source present in both train and val).
    2. Subject identity leakage (same subject/person present in both train and val).
    """
    dataset_path = Path(dataset_dir)
    train_dir = dataset_path / "train"
    val_dir = dataset_path / "val"

    if not train_dir.exists() or not val_dir.exists():
        print(f"[!] Error: Directory '{dataset_dir}' does not contain valid 'train' and 'val' subdirectories.")
        print(f"    Please ensure '{dataset_dir}' exists or run preprocessing first.")
        return

    print("=" * 70)
    print(f" 🔍 DATASET LEAKAGE AUDIT FOR: '{dataset_dir}'")
    print("=" * 70)

    train_sources = defaultdict(set)
    val_sources = defaultdict(set)
    
    train_subjects = defaultdict(set)
    val_subjects = defaultdict(set)

    train_count = 0
    val_count = 0

    # Scan Train Set
    for img_path in train_dir.rglob("*"):
        if img_path.suffix.lower() in {'.jpg', '.jpeg', '.png', '.bmp'}:
            train_count += 1
            info = extract_source_info(img_path.name)
            train_sources[info["source_file_stem"]].add(img_path.name)
            if info["subject_id"]:
                train_subjects[info["subject_id"]].add(img_path.name)

    # Scan Val Set
    for img_path in val_dir.rglob("*"):
        if img_path.suffix.lower() in {'.jpg', '.jpeg', '.png', '.bmp'}:
            val_count += 1
            info = extract_source_info(img_path.name)
            val_sources[info["source_file_stem"]].add(img_path.name)
            if info["subject_id"]:
                val_subjects[info["subject_id"]].add(img_path.name)

    print(f"\n📊 Summary Statistics:")
    print(f"  • Total Train Samples: {train_count:,}")
    print(f"  • Total Val Samples:   {val_count:,}")
    print(f"  • Total Train Source Files/Videos: {len(train_sources):,}")
    print(f"  • Total Val Source Files/Videos:   {len(val_sources):,}")

    # Check 1: Source File / Video Stem Overlap
    overlapping_sources = set(train_sources.keys()).intersection(set(val_sources.keys()))
    
    print("\n" + "-" * 70)
    print(" 🚨 AUDIT RESULT 1: Source File / Frame Leakage")
    print("-" * 70)

    if overlapping_sources:
        leaked_val_samples = sum(len(val_sources[s]) for s in overlapping_sources)
        leakage_pct = (leaked_val_samples / val_count) * 100 if val_count > 0 else 0.0

        print(f" [CRITICAL LEAKAGE DETECTED]")
        print(f"  • Overlapping Source Files/Videos: {len(overlapping_sources):,} files")
        print(f"  • Leaked Validation Crops: {leaked_val_samples:,} / {val_count:,} ({leakage_pct:.2f}% of Val set)")
        print(f"\n  Sample Leaked Source Files (first 5):")
        for src in list(overlapping_sources)[:5]:
            print(f"    - Source Stem: '{src}' | Train crops: {len(train_sources[src])}, Val crops: {len(val_sources[src])}")
    else:
        print(" [CLEAN] No source file / video frame overlaps detected between train and val.")

    # Check 2: Subject ID Overlap
    print("\n" + "-" * 70)
    print(" 🚨 AUDIT RESULT 2: Subject / Identity Leakage")
    print("-" * 70)

    if train_subjects and val_subjects:
        overlapping_subjects = set(train_subjects.keys()).intersection(set(val_subjects.keys()))
        if overlapping_subjects:
            leaked_subj_val_samples = sum(len(val_subjects[s]) for s in overlapping_subjects)
            subj_leakage_pct = (leaked_subj_val_samples / val_count) * 100 if val_count > 0 else 0.0
            
            print(f" [CRITICAL SUBJECT LEAKAGE DETECTED]")
            print(f"  • Total Unique Subjects Tracked: {len(train_subjects | val_subjects):,}")
            print(f"  • Overlapping Subjects in both Train & Val: {len(overlapping_subjects):,} subjects")
            print(f"  • Validation Crops from Train Subjects: {leaked_subj_val_samples:,} / {val_count:,} ({subj_leakage_pct:.2f}%)")
            print(f"\n  Sample Leaked Subject IDs (first 5):")
            for sub in list(overlapping_subjects)[:5]:
                print(f"    - Subject: '{sub}' | Train crops: {len(train_subjects[sub])}, Val crops: {len(val_subjects[sub])}")
        else:
            print(" [CLEAN] No subject identity overlaps detected between train and val.")
    else:
        print(" [NOTE] Could not parse explicit subject IDs from file naming conventions.")

    print("\n" + "=" * 70)
    print(" 💡 RECOMMENDATION")
    print("=" * 70)
    if overlapping_sources or (train_subjects and val_subjects and overlapping_subjects):
        print(" Data leakage detected! Your validation score will be artificially inflated.")
        print(" To fix this:")
        print(" 1. Group source files by Subject ID / Video ID before splitting.")
        print(" 2. Perform GroupKFold or GroupSplit so 100% of a subject's images remain in ONE split.")
    else:
        print(" Train and Validation splits appear isolated by source file.")
    print("=" * 70)

if __name__ == "__main__":
    target_dir = sys.argv[1] if len(sys.argv) > 1 else "processed_dataset"
    audit_dataset_leakage(target_dir)
